"""Feature: rename chains and domains from the Protein Outliner.

The Rename button drives ``proteinblender.rename_domain`` with an explicit
``target_item_id`` + ``item_type``. A rename must (a) show on the outliner row
immediately and (b) survive an outliner rebuild - domains persist through the
wrapper's domain.name, chains through the list item's ``chain_custom_names``
JSON map (chain rows are otherwise regenerated from auth_chain_id_map).
"""

import json
import pytest
import bpy
import helpers as H


def _build_outliner():
    H.scene_manager_module().build_outliner_hierarchy(bpy.context)


def _chain_items(mid):
    return [it for it in bpy.context.scene.outliner_items
            if it.item_type == "CHAIN" and it.parent_id == mid]


def _row(item_id):
    return next((it for it in bpy.context.scene.outliner_items
                 if it.item_id == item_id), None)


@pytest.mark.integration
def test_rename_chain_persists_across_outliner_rebuild(scene, sm, multi_chain):
    mid = multi_chain
    _build_outliner()
    chain = _chain_items(mid)[0]
    chain_item_id = chain.item_id
    chain_idx = str(chain.chain_id)
    assert chain.name != "Heavy Chain"

    res = bpy.ops.proteinblender.rename_domain(
        'EXEC_DEFAULT', target_item_id=chain_item_id, item_type='CHAIN',
        new_name="Heavy Chain")
    assert res == {'FINISHED'}

    # Immediate: the row shows the new name.
    assert _row(chain_item_id).name == "Heavy Chain"

    # Persisted on the list item as JSON (independent of the outliner row).
    list_item = H.list_item(mid)
    stored = json.loads(list_item.chain_custom_names)
    assert stored.get(chain_idx) == "Heavy Chain"

    # Survives a full outliner rebuild (chain rows are otherwise regenerated).
    _build_outliner()
    assert _row(chain_item_id).name == "Heavy Chain"


@pytest.mark.integration
def test_rename_chain_updates_the_row_tooltip_not_just_its_label(scene, sm, multi_chain):
    """The hover tooltip must name the chain the user just named.

    ``rename_domain`` wrote the new label onto every matching outliner row but
    left ``row.tooltip``, which is only regenerated by
    ``build_outliner_hierarchy``. So the row read "Alpha Globin" while hovering
    it still said "Chain: Chain A" - until something else happened to rebuild
    the outliner, at which point it silently corrected itself.

    Found by the save/load round-trip lane: the reopened file (which rebuilds
    the outliner on load) disagreed with the live scene, and the reopened one
    was the correct one.
    """
    mid = multi_chain
    _build_outliner()
    chain = _chain_items(mid)[0]
    chain_item_id = chain.item_id
    assert "Chain A" in chain.tooltip, (
        f"precondition: the tooltip should start out naming the chain, got "
        f"{chain.tooltip!r}")

    assert bpy.ops.proteinblender.rename_domain(
        'EXEC_DEFAULT', target_item_id=chain_item_id, item_type='CHAIN',
        new_name="Alpha Globin") == {'FINISHED'}

    row = _row(chain_item_id)
    assert row.name == "Alpha Globin"
    assert "Alpha Globin" in row.tooltip, (
        f"the row label was renamed but its tooltip still reads {row.tooltip!r}")


@pytest.mark.integration
def test_rename_chain_survives_the_undo_redo_reconstruction(scene, sm, multi_chain):
    """A renamed chain must not be wiped by the undo/redo handler.

    ``sync_molecule_list_after_undo`` rebuilds ``scene.molecule_list_items``
    from the wrapper registry: it snapshots every persistent field, clears the
    collection, re-adds a row per molecule and writes the snapshot back
    (``scene_manager._snapshot_list_item`` / ``_restore_list_item``). Any field
    missing from that snapshot is silently reset to its default - which is the
    documented "Save/load wiped every persisted field" regression, and the
    reason the snapshot function exists at all.

    ``chain_custom_names`` was added later, by the chain-rename feature, and
    was never added to the snapshot. It is the only home a chain name has
    (rows are regenerated from ``auth_chain_id_map`` on every rebuild), so the
    rename is gone the first time the user presses Ctrl+Z.

    The handler is driven directly with the state a real undo hands it -
    Blender has restored the rows and objects while the Python singleton still
    holds stale wrappers - because Blender's undo stack is not reliable in
    ``--background``. Ground truth is the literal string this test set, which
    no add-on code contributes to.
    """
    mid = multi_chain
    _build_outliner()
    chain = _chain_items(mid)[0]
    chain_item_id = chain.item_id
    chain_idx = str(chain.chain_id)

    assert bpy.ops.proteinblender.rename_domain(
        'EXEC_DEFAULT', target_item_id=chain_item_id, item_type='CHAIN',
        new_name="Heavy Chain") == {'FINISHED'}
    assert json.loads(H.list_item(mid).chain_custom_names)[chain_idx] == "Heavy Chain"

    # The post-undo condition: rows and objects survive, the wrapper does not,
    # so the handler takes its reconstruct-and-rebuild path.
    del sm.molecules[mid]
    H.scene_manager_module().sync_molecule_list_after_undo()

    item = H.list_item(mid)
    assert item is not None, "the molecule row did not survive the undo handler"
    stored = json.loads(item.chain_custom_names or "{}")
    assert stored.get(chain_idx) == "Heavy Chain", (
        f"the chain rename was wiped by the undo handler: {stored!r}. "
        "Every persistent MoleculeListItem field must be carried by "
        "scene_manager._snapshot_list_item.")

    # And it still shows, which is what the user actually notices.
    _build_outliner()
    assert _row(chain_item_id).name == "Heavy Chain"


@pytest.mark.integration
def test_rename_chain_blank_restores_default(scene, sm, multi_chain):
    mid = multi_chain
    _build_outliner()
    chain = _chain_items(mid)[0]
    cid = chain.item_id
    default_name = chain.name

    bpy.ops.proteinblender.rename_domain(
        'EXEC_DEFAULT', target_item_id=cid, item_type='CHAIN', new_name="Temp")
    assert _row(cid).name == "Temp"

    # A blank name clears the override, restoring the default after a rebuild.
    bpy.ops.proteinblender.rename_domain(
        'EXEC_DEFAULT', target_item_id=cid, item_type='CHAIN', new_name="")
    _build_outliner()
    assert _row(cid).name == default_name


@pytest.mark.integration
def test_rename_domain_persists_on_the_wrapper(scene, sm, multi_chain):
    mid = multi_chain
    scene.selected_molecule_id = mid
    # Split chain A so real DOMAIN rows exist.
    assert H.split_domain_from_outliner(mid, "A", 1, 50) == {"FINISHED"}
    _build_outliner()

    dom_row = next(it for it in scene.outliner_items if it.item_type == "DOMAIN")
    dom_id = dom_row.item_id

    res = bpy.ops.proteinblender.rename_domain(
        'EXEC_DEFAULT', target_item_id=dom_id, item_type='DOMAIN',
        new_name="Catalytic")
    assert res == {'FINISHED'}
    assert _row(dom_id).name == "Catalytic"

    # Ground truth: the wrapper's domain model carries the new name.
    mol = sm.molecules[mid]
    assert mol.domains[dom_id].name == "Catalytic"

    # And it survives an outliner rebuild.
    _build_outliner()
    assert _row(dom_id).name == "Catalytic"
